version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb-vylex:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-custom-data:/data/mongodb-data

volumes:
  mysql-data:
    driver: local
  mongodb-custom-data:
    driver: local